import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import type { AgentResult, GeneratedFilePayload, ProjectState } from "@/lib/project-types";

type FileJsonPayload = {
  files?: Array<{
    path?: unknown;
    content?: unknown;
    language?: unknown;
  }>;
};

export async function writeGeneratedFiles(projectId: string, files: GeneratedFilePayload[]) {
  const root = path.resolve(process.cwd(), "generated-projects", projectId);
  await mkdir(root, { recursive: true });

  const written: GeneratedFilePayload[] = [];

  for (const file of files) {
    const safePath = sanitizeRelativePath(file.path);
    const target = path.resolve(root, safePath);

    if (!target.startsWith(root + path.sep)) {
      throw new Error(`Unsafe generated file path: ${file.path}`);
    }

    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, file.content, "utf8");
    written.push({
      path: safePath,
      content: file.content,
      language: file.language || inferLanguage(safePath),
    });
  }

  return written;
}

export function extractGeneratedFiles(result: AgentResult, project: ProjectState) {
  if (result.generatedFiles?.length) return normalizeFiles(result.generatedFiles);

  const parsed = parseFilesFromOutput(result.output);
  if (parsed.length) return parsed;

  return buildFallbackProjectFiles(project, result.output);
}

export function formatGeneratedFileSummary(files: GeneratedFilePayload[]) {
  return [
    "## Generated Files",
    "",
    ...files.map((file) => `- \`${file.path}\` (${file.language || inferLanguage(file.path)})`),
  ].join("\n");
}

function parseFilesFromOutput(output: string) {
  const jsonBlock = output.match(/```json\s*([\s\S]*?)```/i);
  if (!jsonBlock?.[1]) return [];

  try {
    const payload = JSON.parse(jsonBlock[1]) as FileJsonPayload;
    return normalizeFiles(
      (payload.files || []).flatMap((file) => {
        if (typeof file.path !== "string" || typeof file.content !== "string") return [];
        return [
          {
            path: file.path,
            content: file.content,
            language: typeof file.language === "string" ? file.language : undefined,
          },
        ];
      })
    );
  } catch {
    return [];
  }
}

function normalizeFiles(files: GeneratedFilePayload[]) {
  const seen = new Set<string>();
  return files.flatMap((file) => {
    const safePath = sanitizeRelativePath(file.path);
    if (seen.has(safePath)) return [];
    seen.add(safePath);
    return [
      {
        path: safePath,
        content: file.content,
        language: file.language || inferLanguage(safePath),
      },
    ];
  });
}

function sanitizeRelativePath(filePath: string) {
  const normalized = filePath.replaceAll("\\", "/").replace(/^\/+/, "");
  const parts = normalized.split("/").filter(Boolean);

  if (!parts.length || parts.some((part) => part === "." || part === "..")) {
    throw new Error(`Unsafe generated file path: ${filePath}`);
  }

  return parts.join("/");
}

function inferLanguage(filePath: string) {
  const ext = path.extname(filePath).slice(1);
  if (ext === "tsx" || ext === "ts" || ext === "json" || ext === "css" || ext === "md") return ext;
  return "text";
}

function buildFallbackProjectFiles(project: ProjectState, codeOutput: string): GeneratedFilePayload[] {
  const title = buildProjectTitle(project.idea);
  const description =
    project.idea.trim() ||
    "A focused generated application created from the multi-agent coding workflow.";

  return [
    {
      path: "package.json",
      language: "json",
      content: JSON.stringify(
        {
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "eslint",
          },
          dependencies: {
            next: "latest",
            react: "latest",
            "react-dom": "latest",
          },
          devDependencies: {
            "@types/node": "latest",
            "@types/react": "latest",
            "@types/react-dom": "latest",
            eslint: "latest",
            "eslint-config-next": "latest",
            typescript: "latest",
          },
        },
        null,
        2
      ),
    },
    {
      path: "app/layout.tsx",
      language: "tsx",
      content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(title)},
  description: "Generated by AgentOS Coder",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { TaskBoard } from "@/components/task-board";
import { projectProfile } from "@/lib/project-data";

export default function Page() {
  return (
    <main className="min-h-screen bg-[#090d12] text-slate-100">
      <TaskBoard profile={projectProfile} />
    </main>
  );
}
`,
    },
    {
      path: "components/task-board.tsx",
      language: "tsx",
      content: `"use client";

import { useMemo, useState } from "react";

import type { ProjectProfile, TaskStatus } from "@/lib/project-data";

const statusLabels: Record<TaskStatus | "all", string> = {
  all: "All",
  todo: "Todo",
  active: "Active",
  review: "Review",
  done: "Done",
};

export function TaskBoard({ profile }: { profile: ProjectProfile }) {
  const [filter, setFilter] = useState<TaskStatus | "all">("all");

  const visibleTasks = useMemo(() => {
    if (filter === "all") return profile.tasks;
    return profile.tasks.filter((task) => task.status === filter);
  }, [filter, profile.tasks]);

  const completed = profile.tasks.filter((task) => task.status === "done").length;
  const progress = Math.round((completed / profile.tasks.length) * 100);

  return (
    <div className="mx-auto flex w-full max-w-7xl flex-col gap-6 px-6 py-8">
      <header className="flex flex-col gap-4 border-b border-white/10 pb-6 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <p className="text-sm font-medium text-cyan-300">Generated workspace</p>
          <h1 className="mt-2 max-w-4xl text-3xl font-semibold text-white md:text-5xl">{profile.title}</h1>
          <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">{profile.description}</p>
        </div>
        <div className="rounded-lg border border-cyan-300/20 bg-cyan-300/10 px-4 py-3">
          <p className="text-xs uppercase text-cyan-200/70">Delivery progress</p>
          <p className="mt-1 text-3xl font-semibold text-cyan-100">{progress}%</p>
        </div>
      </header>

      <section className="grid gap-3 md:grid-cols-4">
        {profile.metrics.map((metric) => (
          <div key={metric.label} className="rounded-lg border border-white/10 bg-white/[0.04] p-4">
            <p className="text-xs text-slate-500">{metric.label}</p>
            <p className="mt-2 text-2xl font-semibold text-slate-50">{metric.value}</p>
            <p className="mt-1 text-xs text-slate-400">{metric.detail}</p>
          </div>
        ))}
      </section>

      <section className="grid gap-6 lg:grid-cols-[260px_minmax(0,1fr)]">
        <aside className="rounded-lg border border-white/10 bg-white/[0.04] p-4">
          <h2 className="text-sm font-semibold">Status Filters</h2>
          <div className="mt-3 grid gap-2">
            {(Object.keys(statusLabels) as Array<TaskStatus | "all">).map((status) => (
              <button
                key={status}
                onClick={() => setFilter(status)}
                className={\`rounded-lg border px-3 py-2 text-left text-sm transition \${
                  filter === status
                    ? "border-cyan-300/40 bg-cyan-300/10 text-cyan-100"
                    : "border-white/10 bg-white/[0.03] text-slate-400 hover:text-slate-100"
                }\`}
              >
                {statusLabels[status]}
              </button>
            ))}
          </div>
        </aside>

        <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
          {visibleTasks.map((task) => (
            <article key={task.id} className="rounded-lg border border-white/10 bg-white/[0.04] p-4">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-xs uppercase text-slate-500">{task.area}</p>
                  <h3 className="mt-2 text-base font-semibold text-slate-50">{task.title}</h3>
                </div>
                <span className="rounded-lg border border-white/10 bg-white/[0.06] px-2 py-1 text-xs capitalize text-slate-300">
                  {task.status}
                </span>
              </div>
              <p className="mt-3 text-sm leading-6 text-slate-400">{task.summary}</p>
              <div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10">
                <div className="h-full rounded-full bg-cyan-300" style={{ width: \`\${task.progress}%\` }} />
              </div>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}
`,
    },
    {
      path: "lib/project-data.ts",
      language: "ts",
      content: `export type TaskStatus = "todo" | "active" | "review" | "done";

export type ProjectProfile = {
  title: string;
  description: string;
  metrics: Array<{
    label: string;
    value: string;
    detail: string;
  }>;
  tasks: Array<{
    id: string;
    title: string;
    area: string;
    summary: string;
    status: TaskStatus;
    progress: number;
  }>;
};

export const projectProfile: ProjectProfile = {
  title: ${JSON.stringify(title)},
  description: ${JSON.stringify(description)},
  metrics: [
    { label: "Active tracks", value: "4", detail: "Product, UI, data, QA" },
    { label: "Open tasks", value: "8", detail: "Prioritized for the first release" },
    { label: "Review queue", value: "2", detail: "Ready for stakeholder feedback" },
    { label: "Release confidence", value: "82%", detail: "Based on current completion" },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Define core user journey",
      area: "Product",
      summary: "Map the primary workflow from entry point to successful completion.",
      status: "done",
      progress: 100,
    },
    {
      id: "task-2",
      title: "Build dashboard overview",
      area: "Interface",
      summary: "Create a scan-friendly summary with metrics, status, and priority signals.",
      status: "active",
      progress: 68,
    },
    {
      id: "task-3",
      title: "Add filtering controls",
      area: "Interaction",
      summary: "Let operators focus on todo, active, review, and completed work.",
      status: "review",
      progress: 88,
    },
    {
      id: "task-4",
      title: "Prepare release checklist",
      area: "QA",
      summary: "Capture manual checks and blockers before the first handoff.",
      status: "todo",
      progress: 20,
    },
  ],
};
`,
    },
    {
      path: "app/globals.css",
      language: "css",
      content: `@import "tailwindcss";

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
  background: #090d12;
}
`,
    },
    {
      path: "README.md",
      language: "md",
      content: `# ${title}

Generated by AgentOS Coder.

## Original Idea

${project.idea}

## Generated Files

- \`app/page.tsx\` renders the main app shell.
- \`components/task-board.tsx\` contains the interactive dashboard.
- \`lib/project-data.ts\` stores typed starter data.
- \`app/globals.css\` sets global styling.

## Code Agent Notes

${codeOutput}
`,
    },
  ];
}

function buildProjectTitle(idea: string) {
  const normalized = idea.trim().replace(/\s+/g, " ");
  if (!normalized) return "Generated Agent App";
  if (normalized.length <= 72) return normalized;
  return `${normalized.slice(0, 69).trim()}...`;
}
